# Generated by Django 5.2.17 on 2026-10-01 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Artista')),
                ('genero', models.CharField(max_length=50, verbose_name='Género Musical')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='artistas/', verbose_name='Imagen del Artista')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Recinto')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('capacidad_maxima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad Máxima')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recintos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Evento')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Banner Promocional')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20, verbose_name='Estado del Evento')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.artista', verbose_name='Artista')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.recinto', verbose_name='Recinto')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(max_length=50, verbose_name='Nombre del Sector')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('stock_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Total')),
                ('stock_disponible', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Disponible')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['precio'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'nombre_sector'), name='unique_sector_por_evento'), models.CheckConstraint(condition=models.Q(('stock_disponible__gte', 0)), name='check_stock_disponible_non_negative'), models.CheckConstraint(condition=models.Q(('stock_disponible__lte', models.F('stock_total'))), name='check_stock_disponible_lte_total'), models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='check_precio_non_negative')],
            },
        ),
    ]
