# Generated by Django 5.2.17 on 2026-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_artista_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
