# Generated by Django 5.2.17 on 2026-10-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_artista_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recinto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='unique_sector_por_evento',
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='check_stock_disponible_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='check_stock_disponible_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='check_precio_non_negative',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='recinto',
            name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='stock_total',
        ),
        migrations.AddField(
            model_name='sector',
            name='capacidad',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='genero',
            field=models.CharField(default='Música', max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.artista'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.recinto'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='ciudad',
            field=models.CharField(default='Santiago', max_length=100),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sector',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre_sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sector',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sector',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
