# Generated by Django 5.2.17 on 2026-10-02 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_alter_artista_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carro de Compras',
                'verbose_name_plural': 'Carros de Compras',
            },
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Solicitada')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Agregado')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carro', verbose_name='Carro de Compras')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carro', to='eventos.sector', verbose_name='Sector Seleccionado')),
            ],
            options={
                'verbose_name': 'Item de Carro',
                'verbose_name_plural': 'Items de Carro',
                'constraints': [models.UniqueConstraint(fields=('carro', 'sector'), name='unique_sector_en_carro')],
            },
        ),
    ]
