# Generated by Django 5.2.17 on 2026-10-01 17:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Orden')),
                ('stock_descontado', models.BooleanField(default=False, help_text='Indica si el stock ya fue procesado en el catálogo.', verbose_name='Stock Descontado')),
                ('stock_repuesto', models.BooleanField(default=False, help_text='Garantiza que una orden cancelada solo reponga stock una vez.', verbose_name='Stock Repuesto')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario Histórico')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden', to='eventos.sector', verbose_name='Sector Comprado')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Orden',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código UUID Único')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('estado', models.CharField(choices=[('VÁLIDA', 'Válida'), ('USADA', 'Usada'), ('ANULADA', 'Anulada')], default='VÁLIDA', max_length=20, verbose_name='Estado de la Entrada')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_emitidas', to='eventos.sector', verbose_name='Sector Asignado')),
            ],
            options={
                'verbose_name': 'Entrada / Ticket',
                'verbose_name_plural': 'Entradas / Tickets',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
